apiVersion: apps/v1
kind: Deployment
metadata:
  name: silicon
spec:
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    spec:
      containers:
        - name: silicon
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 500m
              memory: 1596Mi
          readinessProbe: null
          livenessProbe: null
