apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: postgres
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 100m
              memory: 150Mi
