apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tdm-msds-crucible
resources:
  - github.com/CrucibleSDS/k8s-base/silicon?ref=ed9d78f0a7e9d3fd9288aab7a4dc7cd7c7f0398f

patchesStrategicMerge:
  - overlays/deployment.yaml
  - overlays/configmap.yaml

images:
  - name: ghcr.io/cruciblesds/silicon
    digest: sha256:3b0f6d0945cd2521913db0baa016722bd1fd9ef2b49791bf0e0c5038047e2237
