apiVersion: apps/v1
kind: Deployment
metadata:
  name: merckury
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
        - name: merckury
          resources:
            requests:
              cpu: 50m
              memory: 80Mi
            limits:
              cpu: 300m
              memory: 2000Mi
