apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tdm-msds-crucible
resources:
  - github.com/CrucibleSDS/k8s-base/postgres?ref=main

patchesStrategicMerge:
  - overlays/deployment.yaml
