apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tdm-msds-crucible
resources:
  - github.com/CrucibleSDS/k8s-base/meilisearch?ref=main
  - ./ingress.yaml

patchesStrategicMerge:
  - overlays/deployment.yaml
